CREATE TABLE IF NOT EXISTS raw_traffic_accidents (
    crash_id SERIAL PRIMARY KEY,
    crash_date TIMESTAMP,
    traffic_control_device TEXT,
    weather_condition TEXT,
    lighting_condition TEXT,
    first_crash_type TEXT,
    trafficway_type TEXT,
    alignment TEXT,
    roadway_surface_cond TEXT,
    road_defect TEXT,
    crash_type TEXT,
    intersection_related BOOLEAN,
    damage TEXT,
    prim_contributory_cause TEXT,
    num_units INT,
    most_severe_injury TEXT,
    injuries_total INT,
    injuries_fatal INT,
    injuries_incapacitating INT,
    injuries_non_incapacitating INT,
    injuries_reported_not_evident INT,
    injuries_no_indication INT,
    crash_hour INT,
    crash_day_of_week INT,
    crash_month INT,
    UNIQUE (
        crash_date, crash_hour, traffic_control_device, weather_condition, lighting_condition,
        first_crash_type, trafficway_type, alignment, roadway_surface_cond, road_defect,
        crash_type, intersection_related, damage, prim_contributory_cause, num_units,
        most_severe_injury, injuries_total, injuries_fatal, injuries_incapacitating,
        injuries_non_incapacitating, injuries_reported_not_evident, injuries_no_indication,
        crash_day_of_week, crash_month
    )
);
